import './middle.css'
const Middle = () => {
    return (
        <div className="middle">
           <>
           <h5>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis nesciunt ex nisi. Ipsam itaque porro accusamus ipsum animi consequatur id, neque repudiandae rem. Aut minima earum laudantium rem quisquam aliquam nisi veritatis accusamus nemo vel quae voluptatem eaque, exercitationem, aliquid, necessitatibus minus? Dolores illum aspernatur suscipit voluptatem dicta odit doloremque exercitationem quisquam est rem earum, assumenda enim sapiente dolorum ut consectetur maiores vel ad, reiciendis nobis adipisci dolor ullam sed molestias? Minima voluptatum quaerat nihil temporibus repudiandae velit facilis sint praesentium magnam, dolor impedit rerum veniam molestias, vero amet. Voluptatibus, suscipit repellendus officia blanditiis possimus sed laborum repellat nisi ex aperiam libero totam veniam doloremque, perspiciatis corporis! Nam inventore neque enim itaque. Facilis repellat rem similique eius repellendus obcaecati minus.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor iure odio minima, quis, et saepe, autem natus minus inventore voluptatum commodi deleniti illum quo laborum unde hic libero illo nobis magnam dignissimos voluptatibus ab! Expedita consequatur neque perferendis veniam quibusdam maiores distinctio dolorem nobis laborum quas, reiciendis non nemo ratione alias nulla magni obcaecati eos hic earum ut, voluptatibus, quia in ad. Illo commodi adipisci quas, tempore nobis modi! Ullam adipisci porro nemo voluptatem ea optio necessitatibus enim quo similique quae corrupti sapiente reiciendis nobis nihil maiores quas laborum, fuga illum ipsam expedita iste repudiandae numquam modi? Beatae placeat voluptates eos soluta sed. Veritatis molestias maiores in reprehenderit provident tempora voluptatum quos. Quia aliquam, doloremque quis fugit qui repudiandae sed recusandae minus, laboriosam nihil hic vel culpa, quaerat aut. Consequuntur iste nisi, eum ducimus optio quam nihil inventore id odit ipsa minus sed, harum velit a voluptatum voluptatem quos unde consectetur explicabo? Similique deserunt qui distinctio quas eius ratione corrupti saepe </h5>
           </>
        </div>
    );
};

export default Middle;